# Ag3.16

The **[Ag3.16](Ag3.16):  _Anopheles gambiae_ data resource** contains single nucleotide polymorphism (SNP) calls, copy number variant (CNV) calls and SNP haplotypes from whole-genome sequencing of 812 mosquitoes.

More information about this release can be found in the [data resource website](https://www.malariagen.net/data_package/ag315-anopheles-gambiae-data-resource).  

This page provides an introduction to open data resources released as part of `Ag3.16`. 

If you have any questions about this guide or how to use the data, please [start a new discussion](https://github.com/malariagen/vector-public-data/discussions/new) on the malariagen/vector-open-data repo on GitHub. If you find any bugs, please [raise an issue](https://github.com/malariagen/vector-public-data/issues/new/choose).

## Terms of use

Data from this project will be made publicly available before journal publication, subject to the following publication embargo: unless otherwise stated, analyses of project data are ongoing and publications are in preparation by project partners, and it is not permitted to use project data for publication (including any type of communication with the general public) without prior permission from the originating partner studies. The publication embargo will expire 24 months after the data is integrated into the Malaria Genome Vector Observatory data repository, or earlier, if the project partner agrees to remove the embargo before the expiry date.

Although malaria is generally an endemic rather than an epidemic disease, and the focus of this project is on surveillance of disease vectors rather than pathogens, our data terms of use build on MalariaGEN's approach to data sharing, and adopt norms which have been established for rapid sharing of pathogen genomic data during disease outbreaks. The primary rationale for this approach is that malaria remains a public health emergency, where ethically appropriate and rapid sharing of genomic surveillance data can help to detect and respond to biological threats such as new forms of insecticide resistance, and to adapt malaria vector control strategies to different settings and changing circumstances.

The publication embargo for all data on this release will expire on the **11th of March 2028**. 

If you have any questions about the terms of use, please email support@malariagen.net

## Partner studies

- [1333-VO-GH-AMENGA-ETEGO (Ghana)](https://www.malariagen.net/partner_study/1333-vo-gh-amenga-etego/) - _Anopheles gambiae vector surveillance in Ghana_
- [1352-VO-GW-OSORIO (Guinea-Bissau)](https://www.malariagen.net/partner_study/1352-vo-gw-osorio/) - _Evaluation of the susceptibility of malaria vectors to insecticides in Guinea-Bissau_
- [1355-VO-MW-MCCANN (Malawi)](https://www.malariagen.net/partner_study/1355-vo-mw-mccann/) - _Genomic surveillance of Anopheles species in Malawi_

## Whole-genome sequencing and variant calling

All samples in 1333-VO-GH-AMENGA-ETEGO and 1352-VO-GW-OSORIO have been sequenced individually to high coverage using Illumina technology at the Wellcome Sanger Institute. All samples in 1355-VO-MW-MCCANN have been sequenced individually to high coverage using Illumina technology by collaborators at the University of Maryland. These sequence data have then been analysed to identify genetic variants such as single nucleotide polymorphisms (SNPs). After variant calling, both the samples and the variants have been through a range of quality control analyses, to ensure the data are of high quality. Both the raw sequence data and the curated variant calls are openly available for download and analysis. 


For further information about the sequencing and variant calling methods used, please see the [methods page](methods).

## Data hosting

Data from `Ag3.16` are hosted by several different services. 

The SNP data have also been uploaded to Google Cloud, and can be analysed directly within the cloud without having to download or copy any data, including via free interactive computing services such as [Google Colab](https://colab.research.google.com/). Further information about analysing these data in the cloud is provided in the [cloud data access guide](cloud).

## Sample sets

The samples included in `Ag3.16` have been organised into 4 sample sets. 

Each sample set corresponds to a set of mosquito specimens from a contributing study. Study details can be found in the partner studies webpages listed above.

In [1]:
%pip install -qq malariagen_data

In [2]:
import malariagen_data
ag3 = malariagen_data.Ag3()

In [3]:
df_sample_sets = ag3.sample_sets(release="3.16")
df_sample_sets[['study_id','sample_set', 'sample_count']].set_index('study_id')

                                               sample_set  sample_count
study_id
1333-VO-GH-AMENGO-ETEGO  1333-VO-GH-AMENGA-ETEGO-VMF00287           386
1333-VO-GH-AMENGO-ETEGO  1333-VO-GH-AMENGA-ETEGO-VMF00292            35
1352-VO-GW-OSORIO              1352-VO-GW-OSORIO-VMF00280           323
1355-VO-MW-MCCANN              1355-VO-MW-MCCANN-VMF00315            68

Here is a more detailed breakdown of the samples contained within this sample set, summarised by country, year of collection, and species:

In [4]:
df_samples = ag3.sample_metadata(sample_sets="3.16")
df_summary = df_samples.pivot_table(
    index=["study_id","sample_set", "country", "year"], 
    columns=["taxon"],
    values="sample_id", 
    aggfunc=len,
    fill_value=0)
df_summary

taxon                                                                        arabiensis  \
study_id                sample_set                       country       year
1333-VO-GH-AMENGO-ETEGO 1333-VO-GH-AMENGA-ETEGO-VMF00287 Ghana         2019           2
                                                                       2021           9
                        1333-VO-GH-AMENGA-ETEGO-VMF00292 Ghana         2022           0
1352-VO-GW-OSORIO       1352-VO-GW-OSORIO-VMF00280       Guinea-Bissau 2018          20
                                                                       2021          34
1355-VO-MW-MCCANN       1355-VO-MW-MCCANN-VMF00315       Malawi        2022           4
                                                                       2023          59

taxon                                                                        bissau  \
study_id                sample_set                       country       year
1333-VO-GH-AMENGO-ETEGO 1333-VO-GH-AMENGA-ETEGO-VMF00287 Ghana         2019       0
                                                                       2021       0
                        1333-VO-GH-AMENGA-ETEGO-VMF00292 Ghana         2022       0
1352-VO-GW-OSORIO       1352-VO-GW-OSORIO-VMF00280       Guinea-Bissau 2018      31
                                                                       2021      61
1355-VO-MW-MCCANN       1355-VO-MW-MCCANN-VMF00315       Malawi        2022       0
                                                                       2023       0

taxon                                                                        coluzzii  \
study_id                sample_set                       country       year
1333-VO-GH-AMENGO-ETEGO 1333-VO-GH-AMENGA-ETEGO-VMF00287 Ghana         2019        12
                                                                       2021       347
                        1333-VO-GH-AMENGA-ETEGO-VMF00292 Ghana         2022        35
1352-VO-GW-OSORIO       1352-VO-GW-OSORIO-VMF00280       Guinea-Bissau 2018         5
                                                                       2021        27
1355-VO-MW-MCCANN       1355-VO-MW-MCCANN-VMF00315       Malawi        2022         0
                                                                       2023         0

taxon                                                                        gambiae  \
study_id                sample_set                       country       year
1333-VO-GH-AMENGO-ETEGO 1333-VO-GH-AMENGA-ETEGO-VMF00287 Ghana         2019        0
                                                                       2021       14
                        1333-VO-GH-AMENGA-ETEGO-VMF00292 Ghana         2022        0
1352-VO-GW-OSORIO       1352-VO-GW-OSORIO-VMF00280       Guinea-Bissau 2018       69
                                                                       2021       39
1355-VO-MW-MCCANN       1355-VO-MW-MCCANN-VMF00315       Malawi        2022        5
                                                                       2023        0

taxon                                                                        melas  \
study_id                sample_set                       country       year
1333-VO-GH-AMENGO-ETEGO 1333-VO-GH-AMENGA-ETEGO-VMF00287 Ghana         2019      0
                                                                       2021      2
                        1333-VO-GH-AMENGA-ETEGO-VMF00292 Ghana         2022      0
1352-VO-GW-OSORIO       1352-VO-GW-OSORIO-VMF00280       Guinea-Bissau 2018      0
                                                                       2021      0
1355-VO-MW-MCCANN       1355-VO-MW-MCCANN-VMF00315       Malawi        2022      0
                                                                       2023      0

taxon                                                                        unassigned
study_id                sample_set                       country       year
1333-VO-GH-AMENGO-ETEGO 1333-VO-GH-AMENGA-ETEGO-VMF00287 Ghana         2019           0
                                                                       2021           0
                        1333-VO-GH-AMENGA-ETEGO-VMF00292 Ghana         2022           0
1352-VO-GW-OSORIO       1352-VO-GW-OSORIO-VMF00280       Guinea-Bissau 2018          17
                                                                       2021          20
1355-VO-MW-MCCANN       1355-VO-MW-MCCANN-VMF00315       Malawi        2022           0
                                                                       2023           0

Note that there can be multiple sampling sites represented within the same sample set.

## Further reading

We hope this page has provided a useful introduction to the `Ag3.16` data resource. If you would like to start working with these data, please visit the [cloud data access guide](cloud) or the [data download guide](download) or continue browsing the other documentation on this site.

If you have any questions about the data and how to use them, please do get in touch by [starting a new discussion](https://github.com/malariagen/vector-data/discussions/new) on the malariagen/vector-data repository on GitHub.